In [2]:
import numpy as nu
import pandas as pd

**Creating a DataFrame**

In [3]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df= pd.DataFrame(data)

In [4]:
data

{'Name': ['John', 'Anna', 'Peter', 'Linda'],
 'Age': [28, 34, 29, 42],
 'City': ['New York', 'Paris', 'Berlin', 'London'],
 'Salary': [65000, 70000, 62000, 85000]}

***Selection and indexing columns***

In [5]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
columns = ["Name","Age","City","Salary"]
df2 = pd.DataFrame(data_list,columns = columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

***without set columns***

In [6]:
data_list

[['John', 28, 'New York', 65000],
 ['Anna', 34, 'Paris', 70000],
 ['Peter', 29, 'Berlin', 62000],
 ['Linda', 42, 'London', 85000]]

***Set with columns***

In [7]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [8]:
df2['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

In [9]:
df2['Age']

0    28
1    34
2    29
3    42
Name: Age, dtype: int64

In [10]:
df2['City']

0    New York
1       Paris
2      Berlin
3      London
Name: City, dtype: object

In [11]:
df2['Salary']

0    65000
1    70000
2    62000
3    85000
Name: Salary, dtype: int64

***When show the two columns together***

In [12]:
df2[['Name','Salary']]

    Name  Salary
0   John   65000
1   Anna   70000
2  Peter   62000
3  Linda   85000

In [13]:
df2[["Name",'Age']]

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

In [14]:
df2[['Salary','Name']]

   Salary   Name
0   65000   John
1   70000   Anna
2   62000  Peter
3   85000  Linda

***Creating a new columns***

In [15]:
df2['Designation'] = ["Doctor","Eng.","Doctor","Eng."]

In [16]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.

**Remove Columns**

In [17]:
df2.drop('Designation',axis=1)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [18]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.

***Delete a columns permenent***

In [19]:
df2.drop("Designation",axis=1,inplace=True)

In [20]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

***Multiple drop***

In [21]:
df2.drop(["City","Salary"],axis=1)

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

In [22]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [23]:
df2.drop([0],axis=0)

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

In [24]:
df2.drop([0,1],axis=0)

    Name  Age    City  Salary
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

**Selecting Rows**

In [28]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
#when you want to show the selected data by its rows

In [29]:
df2.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [32]:
df2.loc[[1,2]]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000

In [ ]:
#when to you want to show the selected data by its index

In [33]:
df2.iloc[3]

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

In [34]:
df2.iloc[[1,2,0]]

    Name  Age      City  Salary
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
0   John   28  New York   65000

**Selecting Subsets of Rows and Columns**

In [ ]:
#how to select a particular area of data

In [35]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [37]:
df2.loc[[0,1]][["City","Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

In [38]:
df2.loc[[2,3]][["Name","City","Salary"]]

    Name    City  Salary
2  Peter  Berlin   62000
3  Linda  London   85000

**Conditional Selection**

In [ ]:
#>,<,=,<=,>=,==

In [39]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
#I only want to see those people whose age is above 30

In [42]:
df2[df2["Age"]>30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [ ]:
#I only want people whose age is above 30 and their city must be paris

In [45]:
df2[(df2["Age"]>30) & (df2["City"]=='Paris')]

   Name  Age   City  Salary
1  Anna   34  Paris   70000